[package]
name = "fizz_buzz"
version = "0.1.0"
edition = "2021"
authors = ["testrust <testrust123@mail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.4.6"
